# Generated by Django 3.1.4 on 2020-12-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocsSystem', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
