# Generated by Django 3.1.4 on 2021-01-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocsSystem', '0005_auto_20210116_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='timestamp',
        ),
    ]
